[project]
name = "vtkweb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jonas Lukasczyk", email = "jonas.lukasczyk@rptu.de" }
]
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "mpi4py>=4.1.2",
    "trame>=3.13.2",
    "trame-flow>=2.2.2",
    "trame-vtk>=2.11.16",
    "trame-vtklocal>=0.16,<1",
    "trame-vuetify>=3.2.5",
    "vtk>=9.7.0",
]

[project.scripts]
vtkweb = "vtkweb:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]
