from __future__ import annotations

import keyword
import re
from typing import Any

from vtkweb.pipeline import PipelineGraph
from vtkweb.rendering import RenderManager
from vtkweb.views import ViewManager
from vtkweb.workspace import WorkspaceManager


_IDENTIFIER_RE = re.compile(r"[^0-9A-Za-z_]+")


def _emit_call(lines: list[str], call: str, *args: str, assign: str | None = None) -> None:
    lines.append(f"    {assign + ' = ' if assign else ''}{call}(")
    lines.extend(f"        {arg}," for arg in args)
    lines.append("    )")


def export_python_state(
    pipeline: PipelineGraph,
    rendering: RenderManager,
    views: ViewManager,
    workspace: WorkspaceManager,
) -> str:
    """Return the current application state as executable Python source."""

    lines = [
        "# vtkweb Python state file",
        "# Generated by vtkweb. This file is executable Python.",
        "",
        "    ctrl.clear_state()",
    ]

    view_vars: dict[str, str] = {}
    used_names: set[str] = set()

    if views.views:
        lines.append("")
        lines.append("    # Views")

    for index, value in enumerate(views.views, start=1):
        variable = _unique_identifier(
            value.get("name") or f"view_{index}",
            used_names,
            fallback=f"view_{index}",
        )
        view_vars[value["id"]] = variable

        args = [repr(value["type"]), f"name={value.get('name')!r}", f"view_id={value['id']!r}"]
        if value.get("type") == "dummy" and value.get("message") is not None:
            args.append(f"message={value['message']!r}")
        _emit_call(lines, "ctrl.create_view", *args, assign=variable)

        if value.get("type") in {"vtk", "mitsuba"}:
            for property_name in (
                "background_color",
                "world_ambient_color",
                "world_ambient_intensity",
            ):
                property_value = value.get(property_name)
                if property_value is None:
                    continue
                _emit_call(lines, "ctrl.set_view_property", variable, repr(property_name), repr(property_value))

            camera = rendering.get_view_property(value["id"], "camera")
            _emit_call(lines, "ctrl.set_view_property", variable, repr("camera"), repr(camera))

    container_vars: dict[str, str] = {}
    root_id = workspace.state.workspace_root_id
    if root_id is not None:
        lines.append("")
        lines.append("    # Workspace layout")
        root_var = _unique_identifier(
            "root_container", used_names, fallback="root_container"
        )
        container_vars[root_id] = root_var
        _emit_call(lines, "ctrl.create_workspace", f"container_id={root_id!r}", assign=root_var)
        _export_workspace_node(
            lines,
            workspace.state.workspace_nodes,
            root_id,
            container_vars,
            view_vars,
            used_names,
        )

    node_vars: dict[str, str] = {}

    if pipeline.nodes:
        lines.append("")
        lines.append("    # Pipeline nodes")

    for index, (node_id, node) in enumerate(pipeline.nodes.items(), start=1):
        variable = _unique_identifier(
            node.name or f"node_{index}",
            used_names,
            fallback=f"node_{index}",
        )
        node_vars[node_id] = variable

        _emit_call(
            lines, "ctrl.create_node", repr(node.class_name), f"name={node.name!r}",
            f"node_id={node.id!r}", assign=variable,
        )

    if pipeline.edges:
        lines.append("")
        lines.append("    # Pipeline connections")

    for edge in pipeline.edges:
        _emit_call(
            lines, "ctrl.connect_nodes", node_vars[edge.source_node_id],
            node_vars[edge.target_node_id], f"source_port={edge.source_port!r}",
            f"target_port={edge.target_port!r}",
        )

    property_lines: list[str] = []
    input_array_lines: list[str] = []

    for node_id, node in pipeline.nodes.items():
        node_state = pipeline.node_state(node_id)

        for property_name in sorted(node_state.get("properties", {})):
            property_state = node_state["properties"][property_name]
            value = property_state.get("value")

            # None is the default/unset value for many VTK pointer/string
            # properties and does not carry reconstructable state. Skipping it
            # also keeps state files portable across VTK versions whose
            # introspection exposes different nullable object properties.
            if value is None:
                continue

            _emit_call(property_lines, "ctrl.set_node_property", node_vars[node_id], repr(property_name), repr(value))

        input_arrays = node_state.get("input_arrays", {})
        for key in sorted(input_arrays, key=lambda item: int(item)):
            input_state = input_arrays[key]
            value = input_state.get("value")
            if value is None:
                continue

            _emit_call(
                input_array_lines, "ctrl.set_node_input_array", node_vars[node_id],
                repr(int(input_state["index"])), repr(value),
            )

    if property_lines:
        lines.append("")
        lines.append("    # Processor properties")
        lines.extend(property_lines)

    if input_array_lines:
        lines.append("")
        lines.append("    # Input-array selections")
        lines.extend(input_array_lines)

    transfer_functions = dict(getattr(rendering.state, "transfer_functions", {}) or {})
    if transfer_functions:
        lines.append("")
        lines.append("    # Transfer functions")
        for array_name in sorted(transfer_functions):
            _emit_call(lines, "ctrl.set_tf_data", repr(array_name), repr(transfer_functions[array_name]))

    if rendering.representations:
        lines.append("")
        lines.append("    # Representations")

    for index, representation in enumerate(rendering.representations, start=1):
        variable = _unique_identifier(
            f"{node_vars[representation.node_id]}_{representation.kind}",
            used_names,
            fallback=f"representation_{index}",
        )
        ordered_view_ids = [
            view.id for view in rendering.views if view.id in representation.view_ids
        ]

        lines.extend(
            [
                f"    {variable} = ctrl.add_representation(",
                f"        {node_vars[representation.node_id]},",
                f"        output_port={representation.output_port!r},",
                f"        kind={representation.kind!r},",
                "        view_ids=[",
                *[f"            {view_vars[view_id]}," for view_id in ordered_view_ids],
                "        ],",
                f"        representation_id={representation.id!r},",
                "    )",
            ]
        )

        for property_name, property_value in representation.properties.items():
            _emit_call(
                lines, "ctrl.set_representation_property", variable,
                repr(property_name), repr(property_value),
            )

    lines.append("")
    lines.append("    # Active selections")

    if pipeline.active_node_id is not None:
        _emit_call(lines, "ctrl.set_active_node", node_vars[pipeline.active_node_id])

    if rendering.active_view_id is not None:
        _emit_call(lines, "ctrl.set_active_view", view_vars[rendering.active_view_id])

    # The emitter uses four-space indentation for readable nested snippets;
    # state files themselves are plain top-level statements.
    lines = [line[4:] if line.startswith("    ") else line for line in lines]
    lines.append("")
    return "\n".join(lines)


def load_python_state(
    source: str | bytes,
    ctrl: Any,
    *,
    filename: str = "<vtkweb-state>",
) -> None:
    """Execute a vtkweb Python state file with ``ctrl`` available globally.

    Python state files are executable Python code. Only load state files from
    sources you trust. This function intentionally does not attempt to sandbox
    or otherwise restrict the executed code.  State reconstruction is finalized
    by this loader after the state statements complete successfully.
    """

    if isinstance(source, bytes):
        source = source.decode("utf-8")

    namespace: dict[str, Any] = {
        "__file__": filename,
        "__name__": "vtkweb_state_file",
        "ctrl": ctrl,
    }

    code = compile(source, filename, "exec")
    exec(code, namespace, namespace)

    ctrl.finish_state_load()


def _export_workspace_node(
    lines: list[str],
    nodes: dict,
    node_id: str,
    container_vars: dict[str, str],
    view_vars: dict[str, str],
    used_names: set[str],
) -> None:
    node = nodes[node_id]
    variable = container_vars[node_id]

    if node["kind"] == "leaf":
        view_id = node.get("view_id")
        if view_id is not None:
            _emit_call(lines, "ctrl.assign_view_to_container", variable, view_vars[view_id])
        return

    first_id = node["first"]
    second_id = node["second"]
    first_var = _unique_identifier(
        f"container_{first_id[:8]}", used_names, fallback="container_a"
    )
    second_var = _unique_identifier(
        f"container_{second_id[:8]}", used_names, fallback="container_b"
    )
    container_vars[first_id] = first_var
    container_vars[second_id] = second_var

    _emit_call(
        lines, "ctrl.split_container", variable, repr(node["orientation"]),
        f"ratio={float(node['ratio'])!r}", f"first_id={first_id!r}",
        f"second_id={second_id!r}", assign=f"{first_var}, {second_var}",
    )
    _export_workspace_node(
        lines, nodes, first_id, container_vars, view_vars, used_names
    )
    _export_workspace_node(
        lines, nodes, second_id, container_vars, view_vars, used_names
    )


def _unique_identifier(
    value: str,
    used: set[str],
    *,
    fallback: str,
) -> str:
    identifier = _IDENTIFIER_RE.sub("_", value.strip().lower()).strip("_")
    identifier = identifier or fallback

    if identifier[0].isdigit():
        identifier = f"node_{identifier}"

    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_node"

    candidate = identifier
    suffix = 2

    while candidate in used:
        candidate = f"{identifier}_{suffix}"
        suffix += 1

    used.add(candidate)
    return candidate
