from __future__ import annotations

import keyword
import re
from typing import Any

from vtkweb.pipeline import PipelineGraph
from vtkweb.rendering import RenderManager
from vtkweb.views import ViewManager
from vtkweb.workspace import WorkspaceManager


_IDENTIFIER_RE = re.compile(r"[^0-9A-Za-z_]+")


def export_python_state(
    pipeline: PipelineGraph,
    rendering: RenderManager,
    views: ViewManager,
    workspace: WorkspaceManager,
) -> str:
    """Return the current application state as executable Python source."""

    lines = [
        "# vtkweb Python state file",
        "# Generated by vtkweb. This file is executable Python.",
        "",
        "def load(ctrl):",
        "    ctrl.clear_state()",
    ]

    view_vars: dict[str, str] = {}
    used_names: set[str] = set()

    if views.views:
        lines.append("")
        lines.append("    # Views")

    for index, value in enumerate(views.views, start=1):
        variable = _unique_identifier(
            value.get("name") or f"view_{index}",
            used_names,
            fallback=f"view_{index}",
        )
        view_vars[value["id"]] = variable

        kwargs = []
        if value.get("type") == "dummy" and value.get("message") is not None:
            kwargs.append(f"        message={value['message']!r},")

        lines.extend(
            [
                f"    {variable} = ctrl.create_view(",
                f"        {value['type']!r},",
                f"        name={value.get('name')!r},",
                f"        view_id={value['id']!r},",
                *kwargs,
                "    )",
            ]
        )

        if value.get("type") == "vtk":
            background = value.get("background_color")
            if background is not None:
                lines.extend(
                    [
                        "    ctrl.set_view_background_color(",
                        f"        {variable},",
                        f"        {background!r},",
                        "    )",
                    ]
                )

    container_vars: dict[str, str] = {}
    root_id = workspace.state.workspace_root_id
    if root_id is not None:
        lines.append("")
        lines.append("    # Workspace layout")
        root_var = _unique_identifier(
            "root_container", used_names, fallback="root_container"
        )
        container_vars[root_id] = root_var
        lines.extend(
            [
                f"    {root_var} = ctrl.create_workspace(",
                f"        container_id={root_id!r},",
                "    )",
            ]
        )
        _export_workspace_node(
            lines,
            workspace.state.workspace_nodes,
            root_id,
            container_vars,
            view_vars,
            used_names,
        )

    node_vars: dict[str, str] = {}

    if pipeline.nodes:
        lines.append("")
        lines.append("    # Pipeline nodes")

    for index, (node_id, node) in enumerate(pipeline.nodes.items(), start=1):
        variable = _unique_identifier(
            node.name or f"node_{index}",
            used_names,
            fallback=f"node_{index}",
        )
        node_vars[node_id] = variable

        lines.extend(
            [
                f"    {variable} = ctrl.create_node(",
                f"        {node.class_name!r},",
                f"        name={node.name!r},",
                f"        node_id={node.id!r},",
                "    )",
            ]
        )

    if pipeline.edges:
        lines.append("")
        lines.append("    # Pipeline connections")

    for edge in pipeline.edges:
        lines.extend(
            [
                "    ctrl.connect_nodes(",
                f"        {node_vars[edge.source_node_id]},",
                f"        {node_vars[edge.target_node_id]},",
                f"        source_port={edge.source_port!r},",
                f"        target_port={edge.target_port!r},",
                "        sync=False,",
                "    )",
            ]
        )

    property_lines: list[str] = []
    input_array_lines: list[str] = []

    for node_id, node in pipeline.nodes.items():
        node_state = pipeline.node_state(node_id)

        for property_name in sorted(node_state.get("properties", {})):
            property_state = node_state["properties"][property_name]
            property_lines.extend(
                [
                    "    ctrl.set_node_property(",
                    f"        {node_vars[node_id]},",
                    f"        {property_name!r},",
                    f"        {property_state.get('value')!r},",
                    "    )",
                ]
            )

        input_arrays = node_state.get("input_arrays", {})
        for key in sorted(input_arrays, key=lambda item: int(item)):
            input_state = input_arrays[key]
            value = input_state.get("value")
            if value is None:
                continue

            input_array_lines.extend(
                [
                    "    ctrl.set_node_input_array(",
                    f"        {node_vars[node_id]},",
                    f"        {int(input_state['index'])!r},",
                    f"        {value!r},",
                    "    )",
                ]
            )

    if property_lines:
        lines.append("")
        lines.append("    # Processor properties")
        lines.extend(property_lines)

    if input_array_lines:
        lines.append("")
        lines.append("    # Input-array selections")
        lines.extend(input_array_lines)

    representation_vars: dict[str, str] = {}

    if rendering.representations:
        lines.append("")
        lines.append("    # Representations")

    for index, representation in enumerate(rendering.representations, start=1):
        variable = _unique_identifier(
            f"{node_vars[representation.node_id]}_{representation.kind}",
            used_names,
            fallback=f"representation_{index}",
        )
        representation_vars[representation.id] = variable

        ordered_view_ids = [
            view.id for view in rendering.views if view.id in representation.view_ids
        ]

        lines.extend(
            [
                f"    {variable} = ctrl.add_representation(",
                f"        {node_vars[representation.node_id]},",
                f"        output_port={representation.output_port!r},",
                f"        kind={representation.kind!r},",
                "        view_ids=[",
                *[f"            {view_vars[view_id]}," for view_id in ordered_view_ids],
                "        ],",
                f"        representation_id={representation.id!r},",
                "    )",
            ]
        )

        if representation.array_name is not None:
            lines.extend(
                [
                    "    ctrl.set_representation_array(",
                    f"        {variable},",
                    f"        {representation.array_name!r},",
                    f"        association={representation.association!r},",
                    "    )",
                ]
            )

        if representation.color != "#ffffff":
            lines.extend(
                [
                    "    ctrl.set_representation_color(",
                    f"        {variable},",
                    f"        {representation.color!r},",
                    "    )",
                ]
            )

        if representation.scalar_range is not None:
            minimum, maximum = representation.scalar_range
            lines.extend(
                [
                    "    ctrl.set_representation_scalar_range(",
                    f"        {variable},",
                    f"        {minimum!r},",
                    f"        {maximum!r},",
                    "    )",
                ]
            )

    lines.append("")
    lines.append("    # Active selections")

    if pipeline.active_node_id is not None:
        lines.extend(
            [
                "    ctrl.set_active_node(",
                f"        {node_vars[pipeline.active_node_id]},",
                "    )",
            ]
        )

    if rendering.active_view_id is not None:
        lines.extend(
            [
                "    ctrl.set_active_view(",
                f"        {view_vars[rendering.active_view_id]},",
                "    )",
            ]
        )

    lines.extend(
        [
            "",
            "    ctrl.finish_state_load()",
            "",
        ]
    )

    return "\n".join(lines)


def load_python_state(
    source: str | bytes,
    ctrl: Any,
    *,
    filename: str = "<vtkweb-state>",
) -> None:
    """Execute a vtkweb Python state file and call its ``load(ctrl)`` function.

    Python state files are executable Python code. Only load state files from
    sources you trust. This function intentionally does not attempt to sandbox
    or otherwise restrict the executed code.
    """

    if isinstance(source, bytes):
        source = source.decode("utf-8")

    namespace: dict[str, Any] = {
        "__file__": filename,
        "__name__": "vtkweb_state_file",
    }

    code = compile(source, filename, "exec")
    exec(code, namespace, namespace)

    load = namespace.get("load")
    if not callable(load):
        raise ValueError("Python state file must define callable load(ctrl)")

    load(ctrl)


def _export_workspace_node(
    lines: list[str],
    nodes: dict,
    node_id: str,
    container_vars: dict[str, str],
    view_vars: dict[str, str],
    used_names: set[str],
) -> None:
    node = nodes[node_id]
    variable = container_vars[node_id]

    if node["kind"] == "leaf":
        view_id = node.get("view_id")
        if view_id is not None:
            lines.extend(
                [
                    "    ctrl.assign_view_to_container(",
                    f"        {variable},",
                    f"        {view_vars[view_id]},",
                    "    )",
                ]
            )
        return

    first_id = node["first"]
    second_id = node["second"]
    first_var = _unique_identifier(
        f"container_{first_id[:8]}", used_names, fallback="container_a"
    )
    second_var = _unique_identifier(
        f"container_{second_id[:8]}", used_names, fallback="container_b"
    )
    container_vars[first_id] = first_var
    container_vars[second_id] = second_var

    lines.extend(
        [
            f"    {first_var}, {second_var} = ctrl.split_container(",
            f"        {variable},",
            f"        {node['orientation']!r},",
            f"        ratio={float(node['ratio'])!r},",
            f"        first_id={first_id!r},",
            f"        second_id={second_id!r},",
            "    )",
        ]
    )
    _export_workspace_node(
        lines, nodes, first_id, container_vars, view_vars, used_names
    )
    _export_workspace_node(
        lines, nodes, second_id, container_vars, view_vars, used_names
    )


def _unique_identifier(
    value: str,
    used: set[str],
    *,
    fallback: str,
) -> str:
    identifier = _IDENTIFIER_RE.sub("_", value.strip().lower()).strip("_")
    identifier = identifier or fallback

    if identifier[0].isdigit():
        identifier = f"node_{identifier}"

    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_node"

    candidate = identifier
    suffix = 2

    while candidate in used:
        candidate = f"{identifier}_{suffix}"
        suffix += 1

    used.add(candidate)
    return candidate
