from __future__ import annotations

import keyword
import re
from typing import Any

from vtkweb.pipeline import PipelineGraph
from vtkweb.rendering import RenderManager


_IDENTIFIER_RE = re.compile(r"[^0-9A-Za-z_]+")


def export_python_state(
    pipeline: PipelineGraph,
    rendering: RenderManager,
) -> str:
    """Return the current application state as executable Python source."""

    lines = [
        "# vtkweb Python state file",
        "# Generated by vtkweb. This file is executable Python.",
        "",
        "def load(ctrl):",
        "    ctrl.clear_state()",
    ]

    if len(rendering.views) != 1:
        raise RuntimeError(
            "Current vtkweb UI can export state only with one render view"
        )

    view_vars: dict[str, str] = {}
    used_names: set[str] = set()

    if rendering.views:
        lines.append("")
        lines.append("    # Views")

    for index, view in enumerate(rendering.views, start=1):
        variable = _unique_identifier(
            view.name or f"view_{index}",
            used_names,
            fallback=f"view_{index}",
        )
        view_vars[view.id] = variable

        lines.extend(
            [
                f"    {variable} = ctrl.restore_view(",
                f"        name={view.name!r},",
                f"        view_id={view.id!r},",
                "    )",
            ]
        )

        background = rendering.state.views[view.id].get("background_color")
        if background is not None:
            lines.extend(
                [
                    "    ctrl.set_view_background_color(",
                    f"        {variable},",
                    f"        {background!r},",
                    "    )",
                ]
            )

    node_vars: dict[str, str] = {}

    if pipeline.nodes:
        lines.append("")
        lines.append("    # Pipeline nodes")

    for index, (node_id, node) in enumerate(pipeline.nodes.items(), start=1):
        variable = _unique_identifier(
            node.name or f"node_{index}",
            used_names,
            fallback=f"node_{index}",
        )
        node_vars[node_id] = variable

        lines.extend(
            [
                f"    {variable} = ctrl.create_node(",
                f"        {node.class_name!r},",
                f"        name={node.name!r},",
                f"        node_id={node.id!r},",
                "    )",
            ]
        )

    if pipeline.edges:
        lines.append("")
        lines.append("    # Pipeline connections")

    for edge in pipeline.edges:
        lines.extend(
            [
                "    ctrl.connect_nodes(",
                f"        {node_vars[edge.source_node_id]},",
                f"        {node_vars[edge.target_node_id]},",
                f"        source_port={edge.source_port!r},",
                f"        target_port={edge.target_port!r},",
                "        sync=False,",
                "    )",
            ]
        )

    property_lines: list[str] = []
    input_array_lines: list[str] = []

    for node_id, node in pipeline.nodes.items():
        node_state = pipeline.node_state(node_id)

        for property_name in sorted(node_state.get("properties", {})):
            property_state = node_state["properties"][property_name]
            property_lines.extend(
                [
                    "    ctrl.set_node_property(",
                    f"        {node_vars[node_id]},",
                    f"        {property_name!r},",
                    f"        {property_state.get('value')!r},",
                    "    )",
                ]
            )

        input_arrays = node_state.get("input_arrays", {})
        for key in sorted(input_arrays, key=lambda item: int(item)):
            input_state = input_arrays[key]
            value = input_state.get("value")
            if value is None:
                continue

            input_array_lines.extend(
                [
                    "    ctrl.set_node_input_array(",
                    f"        {node_vars[node_id]},",
                    f"        {int(input_state['index'])!r},",
                    f"        {value!r},",
                    "    )",
                ]
            )

    if property_lines:
        lines.append("")
        lines.append("    # Processor properties")
        lines.extend(property_lines)

    if input_array_lines:
        lines.append("")
        lines.append("    # Input-array selections")
        lines.extend(input_array_lines)

    representation_vars: dict[str, str] = {}

    if rendering.representations:
        lines.append("")
        lines.append("    # Representations")

    for index, representation in enumerate(rendering.representations, start=1):
        variable = _unique_identifier(
            f"{node_vars[representation.node_id]}_{representation.kind}",
            used_names,
            fallback=f"representation_{index}",
        )
        representation_vars[representation.id] = variable

        ordered_view_ids = [
            view.id for view in rendering.views if view.id in representation.view_ids
        ]

        lines.extend(
            [
                f"    {variable} = ctrl.add_representation(",
                f"        {node_vars[representation.node_id]},",
                f"        output_port={representation.output_port!r},",
                f"        kind={representation.kind!r},",
                "        view_ids=[",
                *[f"            {view_vars[view_id]}," for view_id in ordered_view_ids],
                "        ],",
                f"        representation_id={representation.id!r},",
                "    )",
            ]
        )

        if representation.array_name is not None:
            lines.extend(
                [
                    "    ctrl.set_representation_array(",
                    f"        {variable},",
                    f"        {representation.array_name!r},",
                    f"        association={representation.association!r},",
                    "    )",
                ]
            )

        if representation.scalar_range is not None:
            minimum, maximum = representation.scalar_range
            lines.extend(
                [
                    "    ctrl.set_representation_scalar_range(",
                    f"        {variable},",
                    f"        {minimum!r},",
                    f"        {maximum!r},",
                    "    )",
                ]
            )

    lines.append("")
    lines.append("    # Active selections")

    if pipeline.active_node_id is not None:
        lines.extend(
            [
                "    ctrl.set_active_node(",
                f"        {node_vars[pipeline.active_node_id]},",
                "    )",
            ]
        )

    if rendering.active_view_id is not None:
        lines.extend(
            [
                "    ctrl.set_active_view(",
                f"        {view_vars[rendering.active_view_id]},",
                "    )",
            ]
        )

    lines.extend(
        [
            "",
            "    ctrl.finish_state_load()",
            "",
        ]
    )

    return "\n".join(lines)


def load_python_state(
    source: str | bytes,
    ctrl: Any,
    *,
    filename: str = "<vtkweb-state>",
) -> None:
    """Execute a vtkweb Python state file and call its ``load(ctrl)`` function.

    Python state files are executable Python code. Only load state files from
    sources you trust. This function intentionally does not attempt to sandbox
    or otherwise restrict the executed code.
    """

    if isinstance(source, bytes):
        source = source.decode("utf-8")

    namespace: dict[str, Any] = {
        "__file__": filename,
        "__name__": "vtkweb_state_file",
    }

    code = compile(source, filename, "exec")
    exec(code, namespace, namespace)

    load = namespace.get("load")
    if not callable(load):
        raise ValueError("Python state file must define callable load(ctrl)")

    load(ctrl)


def _unique_identifier(
    value: str,
    used: set[str],
    *,
    fallback: str,
) -> str:
    identifier = _IDENTIFIER_RE.sub("_", value.strip().lower()).strip("_")
    identifier = identifier or fallback

    if identifier[0].isdigit():
        identifier = f"node_{identifier}"

    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_node"

    candidate = identifier
    suffix = 2

    while candidate in used:
        candidate = f"{identifier}_{suffix}"
        suffix += 1

    used.add(candidate)
    return candidate
